INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Walk on the moon', '14230', 'Neil Armstrong', '', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Oldest living person dies', '44724', 'Jeanne Calment', 'death', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Publish Looking for Alaska', '10053', 'John Green', 'book', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Publish paper on Special Relativity', '9692', 'Albert Einstein', 'science', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Buddy Holly dies', '8184', 'Buddy Holly', 'music,death', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Become president of the United States', '17336', 'Barack Obama', 'position', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Publish A Game of Thrones', '17482', 'George R. R. Martin', 'book', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Break the world record 100 meter sprint', '7954', 'Usain Bolt', 'sport,achievement', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Release ''Are You Experienced''', '9663', 'Jimi Hendrix', 'music', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Publish ''On the Origin of Species''', '18547', 'Charles Darwin', 'book,science', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Become Queen of England', '9422', 'Elizabeth II', '', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Be crowned Emperor of France', '12635', 'Napoleon', 'history', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Become Pope', '27845', 'Pope Francis', 'history', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Become World Chess Champion', '10769', 'Bobby Fischer', 'sport,achievement', '', '');
INSERT INTO `events` (`id`, `title`, `days`, `who`, `type`, `description`, `image`) VALUES (NULL, 'Be defeated at chess by Deep Blue', '11991', 'Garry Kasparov', '', '', '');